name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint CSS
      run: npm run lint
      continue-on-error: true
    
    - name: Build CSS
      run: npm run build
    
    - name: Check build artifacts
      run: |
        test -f dist/shortcut.css || exit 1
        test -f dist/shortcut.min.css || exit 1
        test -f dist/shortcut-without-important.css || exit 1
        test -f dist/shortcut-without-important.min.css || exit 1
        test -f dist/index.d.ts || exit 1
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-files-${{ matrix.node-version }}
        path: dist/

